name: Deploy to Vercel

on:
  push:
    branches: [main]

env:
  VERCEL_ORG_ID: team_Ig1S3sDcM4q8JX0aEIChjGDR
  VERCEL_PROJECT_ID: prj_Txts4fLXWWcVUp25nFYiqvzPvCe0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Production
        run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
