name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_Ig1S3sDcM4q8JX0aEIChjGDR
          vercel-project-id: prj_Txts4fLXWWcVUp25nFYiqvzPvCe0
          vercel-args: '--prod'
          working-directory: ./
